version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/rfServerProject
    runas: ubuntu
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/rfServerProject/
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 20