version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/rfServerProject
    overwrite: yes
permissions:
  - object: /home/ubuntu/rfServerProject/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/env.sh
      timeout: 60
      runas: ubuntu
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
