spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/rfdb?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  cloud:
    aws:
      s3:
    bucket: rf-aws-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
          accessKey: ${S3_ACCESSKEY}
          secretKey: ${S3_SECRETKEY}