spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/rfdb?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true