spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/testdb?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          javax.persistence.jdbc.url
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # google 계정
    password: ${MAIL_PASSWORD} # 발급 받은 앱 비밀번호 (16자리)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

cloud:
  aws:
      s3:
        bucket: ${S3_BUCKET}
      stack:
        auto: false
      region:
        static: ap-northeast-2
      credentials:
        accessKey: ${S3_ACCESSKEY}
        secretKey: ${S3_SECRETKEY}
